# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        source-url: https://nuget.pkg.github.com/Y0annD/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-results-9.0.x
        path: TestResults-9.0.x
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
    - name: Build
      run: dotnet build --no-restore --configuration Release KLVConverter
    - name: Create the package
      run: dotnet pack --configuration release KLVConverter
    - name: Publish the package to GPR
      run: dotnet nuget push KLVConverter/bin/Release/*.nupkg