on:
  push:
    branches: ["master"]
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 9.0.x
            source-url: https://nuget.pkg.github.com/Y0annD/index.json
          env:
            NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        - name: Restore dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --no-restore --configuration Release KLVConverter
        - name: Create the package
          run: dotnet pack --configuration Release KLVConverter
        - name: Publish the package to GPR
          run: dotnet nuget push KLVConverter/bin/Release/*.nupkg
          env:
            NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}